name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: |
          yarn gen
          yarn fmt .
      - run: |
          isDiff=$(git --no-pager diff)

          if [ -n "$isDiff" ]; then
            echo "────────────────────────────────────────"
            echo "This file isn’t up to date"
            echo "────────────────────────────────────────"
            echo ""
            git diff --name-only \
            | sed 's/^/  - /'
            echo ""
            echo "────────────────────────────────────────"
            echo "Actual diff:"
            echo "────────────────────────────────────────"
            echo ""
            git --no-pager diff
            echo ""
            echo "::error::Generated or formatted files are out of date. Please run 'pnpm gen' and 'pnpm fmt .' locally."
            exit 1
          else
            echo "No changes detected. All generated files are up to date."
          fi

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn fmt:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint
